var testdata = [
    "한글",
    "가나다라마바사아자차카타파하",
    "테한스트글",
    "한123abc글",
    "슈퍼마리오 오디세이",
    "마계전기 디스가이아5",
    "원더보이 : 드래곤즈 트랩",
    "NBA 2K 18",
    "뿌요뿌요™테트리스® S",
    "소닉 포시즈",
    "페이트/엑스텔라",
    "슈퍼 봄버맨 R",
    "마리오 카트 8 디럭스7ㅂ",
    "레고 월드",
    "마리오 + 래비드 킹덤 배틀",
    "VOEZ",
    "젤다의 전설 브레스 오브 더 와일드",
    "레고 마블 슈퍼히어로즈2",
    "진격의 거인2",
    "진격의 거인2 -Final Battle-",
    "젤다무쌍 하이랄의 전설들 DX",
    "리디&수르의 아틀리에 ~신비한 그림의 연금술사~",
    "해피 버스데이즈",
    "ARMS",
    "포탈 나이츠",
    "와일드 건즈 리로디드",
    "별의 커비 스타 얼라이즈",
    "배틀 체이서:나이트워 ",
    "스트리트 파이터 30th 애니버서리 콜렉션",
    "블레이블루 크로스 태그 배틀",
    "블레이블루 크로스 태그 배틀 스페셜 에디션",
    "욘더: 클라우드 캐쳐 크로니클",
    "걸☆건 2 ",
    "포켓몬 퀘스트 ",
    "테니스 월드 투어",
    "마리오 테니스 에이스",
    "폴른 레기온 ",
    "영광의 계보",
    "레고 인크레더블",
    "샤이닝 레조넌스 리프레인",
    "소닉 매니아 플러스",
    "태고의 달인",
    " Nintendo Switch 버~전",
    "클로즈드 나이트메어",
    "두근두근 동물랜드",
    "데드 셀",
    "신 대개척시대 : 도시를 만들자",
    "쉐피",
    "사막의 찍찍이 유랑단",
    "거짓말쟁이 공주와 눈 먼 왕자",
    "빅터브란 오버킬 에디션",
    "사이바리아 델타",
    "Little Dragons Café",
    "큐브 크리에이터 X",
    "샐리의 법칙",
    "더블드래곤 4",
    "Deemo",
    "라디오해머 스테이션",
    "던전 러셔",
    "가챠 레이싱 2nd ",
    "오버쿡! 2",
    "SNK히로인즈 ",
    "TAG TEAM FRENZY",
    "NBA® 2K19",
    "마계전기 디스가이아 리파인",
    "레전더리 피싱",
    "사이쿄 콜렉션 Vol.1",
    "스트라이커즈 1945 for Nintendo Switch",
    "(STRIKERS 1945 for Nintendo Switch)",
    "건버드 for Nintendo Switch",
    "(GUNBIRD for Nintendo Switch)",
    "사무라이 에이스 for Nintendo Switch",
    "(Samurai Aces for Nintendo Switch)",
    "솔 디바이드 for Nintendo Switch",
    "(SOL DIVIDE for Nintendo Switch)",
    "전장의 발큐리아 4",
    "드래곤볼 파이터즈",
    "루프란의 지하미궁과 마녀의 여단",
    "갓 워즈 더 컴플리트 레전드",
    "무쌍OROCHI3",
    "무쌍OROCHI3 Ultimate ",
    "다크 소울 리마스터",
    "사이베리아 3 ",
    "저스트 댄스 2019",
    "나의 히어로 원즈 저스티스",
    "뿌요뿌요 e스포츠",
    "요마와리: 떠도는 밤 ",
    "신 요마와리 ~ 떠도는 밤: 심연 ",
    "for Nintendo Switch™",
    "The MISSING",
    " -J.J 맥필드와 추억의 섬",
    "SPORTS PARTY",
    "LEGO DC Super-Villains",
    "월드 오브 파이널 판타지 맥시마",
    "그립: 컴뱃 레이싱",
    "NBA 2K 플레이그라운드 2",
    "Hungry Shark® World",
    "포켓몬스터 레츠고! 피카츄",
    "포켓몬스터 레츠고! 이브이",
    "시드 마이어의 문명 VI",
    "사이쿄 콜렉션 Vol.2",
    "스트라이커즈 1945 II for Nintendo Switch",
    "(STRIKERS 1945 II for Nintendo Switch)",
    "건버드2 for Nintendo Switch",
    "(GUNBIRD2 for Nintendo Switch)",
    "텐가이 for Nintendo Switch",
    "(TENGAI for Nintendo Switch)",
    "드래곤 블레이즈 for Nintendo Switch",
    "(Dragon Blaze for Nintendo Switch)",
    "가면라이더 클라이맥스 스크램블",
    "올드 스쿨 뮤지컬",
    "슈퍼 스매시브라더스 얼티밋",
    "핸드 오브 페이트 2",
    "나쁜 놈을 죽이자",
    "토키",
    "탐정 진구지 사부로 ",
    "프리즘 오브 아이즈",
    "쿠니오 군: 더 월드 클래식 컬렉션",
    "피트니스 복싱",
    "아스테릭스 & 오벨릭스 XXL 2",
    "브이 랠리 4",
    "테일즈 오브 베스페리아 ",
    "REMASTER",
    "뉴 슈퍼 마리오브라더스 U 디럭스 ",
    "Nintendo Labo 버라이어티 키트",
    "기어 클럽 언리미티드 2",
    "Travis Strikes Again",
    " No More Heroes",
    "뮬라카(Mulaka)",
    "아이코노클라스트(Iconoclasts)",
    "페이트 엑스텔라 링크",
    "「OPUS COLLECTION」 ",
    "지구계획 + 영혼의가교",
    "블레이블루 센트럴픽션",
    "미스트랄리아의 마법사",
    "걸즈 앤 판처 드림 탱크 매치 DX",
    "라피스 리 어비스",
    "방구석에 인어아가씨",
    "베이블레이드버스트 배틀 제로",
    "Football Manager 2019 Touch",
    "섬란 카구라 Reflexions",
    "드래곤 마크드 포 데스",
    "칼리굴라 오버도즈",
    "블레이드 아크스 리벨리온 from Shining",
    "슈퍼로봇대전 T",
    "데드 오어 얼라이브 익스트림 3 스칼렛",
    "디스 이즈 더 폴리스 2",
    "건볼트 스트라이커 팩",
    "슈퍼 마리오 파티",
    "레미로어 ~소녀와 이세계와 마도서~",
    "요시 크래프트 월드",
    "디아블로 3 이터널콜렉션",
    "루트 레터 라스트 엔써",
    "역전재판 123 나루호도 셀렉션",
    "FINAL FANTASY X/X-2 HD Remaster",
    "Nintendo Labo: VR 키트",
    "스낵월드 트레져러스 골드",
    "TETRIS® 99",
    "스타링크: 아틀라스를 위한 전투",
    "FINAL FANTASY XII THE ZODIAC AGE",
    "소드 아트 온라인 ",
    "-할로우 리얼라이제이션- ",
    "Deluxe Edition",
    "리틀 프렌즈 - DOGS & CATS -",
    "사이터스 알파",
    "프로젝트 하이라이즈: 아키텍트 에디션",
    "네오 아틀라스 1469",
    "마스 오어 다이!",
    "마키나이츠 -블러드 바고스-",
    "섬란 카구라 PEACH BALL",
    "GUILTY GEAR 20th ",
    "ANNIVERSARY PACK",
    "GUILTY GEAR",
    "길티기어 이그젝스 액센트 코어 플러스 R",
    "Panty Party",
    "인페르노 클라이머 리본",
    "데스티니 커넥트",
    "팀 소닉 레이싱",
    "어쌔신크리드 III 리마스터",
    "루루아의 아틀리에 ~알란드의 연금술사4~",
    "TT 아일 오브 맨",
    "다이달로스 ",
    "~디 어웨이크닝 오브 골든 재즈~",
    "사이쿄 콜렉션 Vol.3",
    "제로 거너 2- for Nintendo Switch",
    "전국 캐논 for Nintendo Switch",
    "GUNBARICH for Nintendo Switch",
    "STRIKERS1945 lll for Nintendo Switch",
    "러브러브 스위츠",
    "~너와 나의 비밀 레시피~",
    "케이던스 오브 하이랄",
    "크립트 오브 더 네크로댄서 ",
    "feat. 젤다의 전설",
    "서바이브! 미스터 큐브",
    "블러드스테인드: 리추얼 오브 더 나이트",
    "슈퍼 마리오 메이커 2",
    "용사 넵튠 ",
    "세계여 우주여 주목하라!!",
    " 얼티밋 RPG 선언!!",
    "갓 이터 3",
    "어웨이: 뜻밖의 여정",
    "Nintendo Labo 로봇 키트",
    "Nintendo Labo 드라이브 키트",
    "칼라드리우스 블레이즈",
    "MARVEL ULTIMATE ALLIANCE 3",
    "The Black Order",
    "레드 팩션: 게릴라 리마스터",
    "2020 도쿄 올림픽 - The Official Video Game ",
    "닌자 세이비어: 리턴 오브 워리어즈",
    "킬라킬 -IF",
    "도라에몽 진구의 목장 이야기",
    "파이어엠블렘 풍화설월",
    "오메가 라비린스 라이프",
    "소드 아트 온라인 ",
    "-페이탈 불릿- ",
    "Complete Edition",
    "에어 컨플릭트 컬렉션",
    "에어 컨플릭트: 시크릿 워",
    "에어 컨플릭트: 퍼시픽 캐리어",
    "드래곤 퀘스트 빌더즈 2",
    "파괴신 시도와 텅 빈 섬",
    "신옥탑 메리스켈터 2",
    "수퍼케인매직제로",
    "그랑브릭슈터",
    "ASTRAL CHAIN(애스트럴 체인)",
    "열혈경파 쿠니오군 외전 리버시티 걸즈",
    "NBA 2K20",
    "슈퍼 커비 헌터즈",
    "Brawlhalla",
    "DAEMON X MACHINA",
    "블레이징 크롬",
    "젤다의 전설 꿈꾸는 섬 ",
    "건볼트 크로니클: 루미너스 어벤저 iX",
    "콘트라 로그 콥스",
    "다크사이더스 2 : 데시니티브 에디션",
    "드래곤 퀘스트 XI S ",
    "지나간 시간을 찾아서 - Definitive Edition",
    "FIFA 20 레거시 에디션",
    "슈퍼로봇대전 V",
    "조이드 와일드 킹 오브 블래스트",
    "미스트오버",
    "얼라이언스 얼라이브 HD Remastered",
    "다운타운 난투행진곡 Mach!!",
    "디즈니 썸썸 페스티벌",
    "Sniper Elite 3 Ultimate Edition ",
    "더 위쳐3",
    "와일드 헌트",
    "컴플리트 에디션 ",
    "오버워치 레전더리 에디션        ",
    "목장이야기 다시 만난 미네랄 타운의 친구들",
    "디지몬 스토리 사이버 슬루스 해커스 메모리",
    "링 피트 어드벤처",
    "더스크 다이버",
    "기가 레커 알트",
    "다크 디보션",
    "루이지 맨션 3",
    "퍼펙트! 슈퍼 몽키 볼",
    "랑그릿사 Ⅰ＆Ⅱ",
    "마리오와 소닉 AT 도쿄 올림픽",
    "트라인 4: 악몽의 왕자",
    "저스트 댄스 2020",
    "열혈외전 멋지다! 코바야시",
    "하베스트문: 매드 대시",
    "WRC 8 FIA 월드 랠리 챔피언십",
    "포켓몬스터 소드",
    "포켓몬스터 실드",
    "ZUMBA® BURN IT UP!",
    "SD건담 지 제네레이션 크로스 레이즈",
    "드래곤 퀘스트 I, II, III",
    "드래곤 퀘스트",
    "드래곤 퀘스트 II 악령의 신들",
    "드래곤 퀘스트 III 전설의 시작",
    "퇴마인법첩 ~요괴지옥변~",
    "좀비 패닉 인 원더랜드 DX",
    "룬 팩토리 4 스페셜",
    "어쌔신 크리드",
    "The Rebel Collection",
    "Football Manager 2020 Touch",
    "몬스터 보이와 저주받은 왕국",
    "사무라이 쇼다운",
    "고스트버스터즈: 더 비디오 게임 리마스터드",
    "닌자 자자마루군 컬렉션",
    "NIPPON 마라톤",
    "닌진: 당근 전쟁",
    "참! 참! 참!",
    "포트나이트",
    "버블보블 4 프렌즈",
    "닌자 박스",
    "라이자의 아틀리에 ",
    "~어둠의 여왕과 비밀의 은신처~",
    "Don't Knock Twice",
    "Fractured Minds",
    "슈퍼로봇대전 X",
    "HEROINE ANTHEM ZERO episode 1",
    "마인크래프트",
    "삽질 기사: 매장된 보물",
    "Sacred Stones",
    "Cuphead",
    "Return of the Obra Dinn",
    "밀크초코",
    "프린세스 메이커 -꿈꾸는 요정-",
    "UNI",
    "파스파투: 배고픈 예술가",
    "CODE SHIFTER",
    "하츠네 미쿠 -프로젝트 디바- MEGA39’s",
    "북바운드 브리게이드",
    "파: 론 세일즈",
    "얼티밋 치킨 호스",
    "다크사이더스 제네시스",
    "쿠나이(KUNAI)",
    "언더 나이트 인버스 엑셀레이트 클레어",
    "3000th Duel",
    "꿀벌 시뮬레이터",
    "쓰론브레이커: 더 위쳐 테일즈",
    "Super Crush KO",
    "Freedom Planet",
    "나의 히어로 원즈 저스티스 2",
    "길고양이 이야기",
    "The Dark Crystal",
    "Age of Resistance Tactics",
    "Kingdom Rush Frontiers",
    "Little Nightmares Complete Edition",
    "사일런트 월드",
    "모여봐요 동물의 숲",
    "원피스 해적무쌍 4",
    "피싱 스타 월드 투어",
    "레일웨이 엠파이어",
    "카오스 코드 -뉴 사인 오브 카타스트로피-",
    "오버패스",
    "Good Job!",
    "Shinsekai Into the Depths™",
    "좀비 아미 트릴로지",
    "기간토사우루스 더 게임",
    "MazM: 지킬 앤 하이드",
    "절체절명도시4 Plus -Summer Memories-",
    "도라에몽 진구의 달 탐사기",
    "짱구는 못말려",
    "태풍을 부르는 불꽃의 카스카베 러너",
    "당신을 기다리는 여우 The Fox Awaits Me",
    "Save Your Nuts",
    "슈퍼 픽셀 레이서즈",
    "The Shapeshifting Detective",
    "프리티 프린세스 메지컬 코디네이트",
    "NARUTO - 나루토- 질풍전 나루티밋 스톰 4 ",
    "ROAD TO BORUTO",
    "마계전기 디스가이아 4 Return",
    "MODEL Debut #nicola/모델 데뷔 니콜라",
    "Machinarium (머시나리움)",
    "성검전설3 TRIALS of MANA ",
    "무빙 아웃",
    "우미하라 카와세 Fresh!",
    "정령의 기사단",
    "베어 너클 4",
    "모노크롬 월드",
    "Goblin Sword",
    "One Step From Eden",
    "Exit the Gungeon",
    "아스팔트 9: 레전드",
    "TT 아일 오브 맨 2",
    "Resolutiion",
    "한계돌파 모에로 크리스탈 H",
    "이스 VIII -Lacrimosa of DANA-",
    "인디비지블",
    "XCOM® 2 Collection",
    "바이오쇼크 인피니트",
    "제노블레이드 크로니클스 ",
    "디피니티브 에디션        ",
    "아우터 월드 (The Outer Worlds)",
    "아메리칸 퓨지티브",
    "포 더 킹",
    "신차원게임 넵튠 VII",
    "NAMCOT COLLECTION",
    "페르소나 5 스크램블 더 팬텀 스트라이커즈",
    "에이오 테니스 2",
    "Atomicrops",
    "Minecraft Dungeons",
    "네모바지 스폰지밥",
    "비키니 시의 전쟁",
    "리하이드레이티드",
    "Pokémon Café Mix",
    "Ninjala",
    "미스터 드릴러 드릴랜드",
    "릴 피싱 로드 트립 어드벤처",
    "Jump Rope Challenge",
    "매일매일 Nintendo Switch 두뇌 트레이닝",
    "캐서린 풀 보디 for Nintendo Switch",
    "북 오브 데몬즈",
    "Superliminal",
    "Doodle God : Evolution",
    "Warparty",
    "CrossCode",
    "테라리아",
    "Death Come True",
    "페이퍼 마리오 종이접기 킹",
    "Ace Angler 낚시 스피릿",
    "Earthfall : Alien Horde",
    "락 오브 에이지 3",
    "Coffee Talk",
    "Creaks (크릭스)",
    "옥토패스 트래블러",
    "페어리 테일",
    "사무라이 스피리츠 네오지오 컬렉션",
    "몽현 Re:Master 번들팩",
    "몽현 Re:Master",
    "몽현 Re:After",
    "베리드 스타즈",
    "Kingdom Rush",
    "호텔 소울즈",
    "스컬리",
    "오니가 우는 나라",
    "저니 투 더 새비지 플래닛",
    "PGA TOUR 2K21",
    "노 스트레이트 로드",
    "Takeshi and Hiroshi",
    "World of Tanks Blitz",
    "JUMP FORCE Deluxe Edition",
    "Deadly Days",
    "The Sinking City",
    "Gleamlight(글림라이트)",
    "휴먼: 폴 플랫",
    "라스트 캠프파이어",
    "West of Dead",
    "아리와 사계절의 비밀",
    "제노블레이드 크로니클스 2",
    "Piffle: 고양이 퍼즐 모험",
    "NBA 2K 21",
    "아비치 인벡터",
    "MO:Astray",
    "네바에(Nevaeh)",
    "Kingdom Rush Origins",
    "Kholat(콜랏)",
    "Hades",
    "WWE 2K Battlegrounds",
    "슈퍼 마리오 Wii 갤럭시 어드벤처",
    "(슈퍼 마리오 3D 컬렉션)",
    "던그리드",
    "Lost Ember",
    "The Coma 2: Vicious Sisters",
    "커비 파이터즈 2",
    "《이스：오리진 (Ys Origin)》",
    "어스나이트",
    "헌팅 시뮬레이터 2",
    "트롤헌터: 아카디아의 수호자",
    "슈퍼 마리오브라더스 35",
    "Spiritfarer®",
    "사이클 질주본능 DX",
    "AstroWings: Space War",
    "FIFA 21 Nintendo Switch™ 레거시 에디션",
    "The Survivalists",
    "동방스펠버블",
    "HARDCORE MECHA",
    "Vigil: The Longest Night",
    "스페이스 크루",
    "Ring of Pain",
    "Outpost Delta",
    "팡 어드벤처스",
    "Construction Simulator 3 - Console Edition",
    "제물과 눈의 세츠나",
    "트랜스포머: 배틀그라운드",
    "네버송 & 핀스트라이프",
    "Neversong (네버송)",
    "Pinstripe (핀스트라이프)",
    "Disc Room",
    "Carto",
    "테니스 월드 투어 2",
    "Control Ultimate Edition",
    "Cloud Version",
    "Yuppie Psycho: Executive Edition",
    "진·여신전생 3 NOCTURNE HD REMASTER",
    "MAD RAT DEAD",
    "가면라이더 메모리 오브 히어로즈",
    "샨테와 일곱 사이렌",
    "Youtubers Life OMG Edition",
    "피크민 3 디럭스",
    "열일하는 UFO",
    "세븐나이츠 - Time Wanderer -",
    "로키",
    "REPLICA",
    "클라우드펑크",
    "천수의 사쿠나히메",
    "KINGDOM HEARTS Melody of Memory",
    "벽람항로 Crosswave",
    "Ori and the Will of the Wisps",
    "Just Dance® 2021",
    "좀비스쿨",
    "카르마나이트",
    "젤다무쌍 대재앙의 시대",
    "태고의 달인 쿵딱! 두 가지 RPG 대모험",
    "QV",
    "스피릿 오브 더 노스",
    "크로노스: 비포 디 애쉬",
    "라이자의 아틀리에2",
    " ~잃어버린 전승과 비밀의 요정~",
    "Immortals Fenyx Rising",
    "Fitness Boxing 2 -Rhythm & Exercise",
    "루트 필름",
    "트로피코 6 - 닌텐도 스위치 에디션",
    "Despotism 3k",
    "스커지브링어",
    "둠 이터널",
    "고스트러너",
    "삼국지14 with 파워업키트",
    "뿌요뿌요™테트리스® 2",
    "그려라, 터치: 두 개의 왕국",
    "Fight of Animals",
    "MONKEY BARRELS",
    "Football Manager 2021 Touch",
    "다이시 던전",
    "마녀의 샘3 Re:Fine ",
    "<인형마녀 아이루디의 이야기>",
    "마리오 카트 라이브: 홈 서킷",
    "DEEMO -Reborn-",
    "Wildfire",
    "Nexomon: Extinction 넥소몬: 멸종",
    "METAL MAX Xeno Reborn",
    "Shakes on a Plane",
    "괴혼 ~굴려라 돌아온 왕자님~",
    "사무라이 포스: 참!",
    "Neoverse 네오버스 트리니티 에디션",
    "Just Shapes & Beats",
    "로스트 스피어",
    "메르헨 포레스트",
    "걸☆건 리턴즈",
    "Touhou Luna Nights(동방 루나 나이츠)",
    "알파카 축구 올스타",
    "문라이터",
    "리틀 나이트메어 2",
    "Super Meat Boy ",
    "슈퍼 마리오 3D 월드 + 퓨리 월드",
    "Among Us",
    "RASPBERRY MASH",
    "Cyber Shadow",
    "Capcom Arcade Stadium",
    "도토리",
    "영웅전설 제로의 궤적: Kai",
    "목장이야기 올리브 타운과 희망의 대지",
    "Empire of Sin(엠파이어 오브 신)",
    "Forward To The Sky (포워드 투 더 스카이)",
    "리갈던전 (Legal Dungeon)",
    "Shady Part of Me",
    "Othercide",
    "Curse of the Dead Gods",
    "BRAVELY DEFAULT II",
    "유루캠Δ VIRTUAL CAMP ～모토스호 편～",
    "시 오브 솔리튜드 - 더 디렉터즈 컷",
    "노블 아르마다: 로스트 월드",
    "Unrailed!",
    "Two Point Hospital",
    "틸트팩: 빙글빙글 대소동",
    "던전 림버스(Dungeon Limbus)",
    "Apex 레전드™",
    "A열차로 가자 시작해요 관광지 개발",
    "Cotton Reboot!",
    "다리우스 코즈믹 레버레이션",
    "다리우스 버스트ACEX+",
    "G다리우스HD（DARIUS G HD）",
    "Figment",
    "파이널소드 DefinitiveEdition",
    "식물 vs. 좀비™",
    "네이버빌의 대난투 컴플리트 에디션",
    "Overcooked! All You Can Eat",
    "BodyQuest - 바디퀘스트",
    "SD건담 지 제네레이션 제네시스",
    "for Nintendo Switch",
    "MazM: 오페라의 유령",
    "모비드: 일곱 명의 사도",
    "BALAN WONDERWORLD",
    "MONSTER HUNTER RISE",
    "Can't Drive This",
    "Give It Up! Bouncy 포기하지마! 바운시",
    "유루캠Δ VIRTUAL CAMP 산기슭 캠핑장 편",
    "스미코구라시 모여 봐요! 스미코 타운",
    "Cozy Grove",
    "Breathedge",
    "WRC 9",
    "PAC-MAN 99",
    "Mad Father",
    "송버드 심포니",
    "칠드런 오브 몰타",
    "영웅전설 벽의 궤적: Kai",
    "틀린 그림 찾기 전집 -우뇌의 달인-",
    "for Nintendo Switch",
    "유그드라 유니온",
    "MathLand - 수학 땅",
    "Smelter",
    "Angels of Death",
    "Olija",
    "Speed 3: Grand Prix 스피드 3: 그랑프리",
    "다함께 쿠키요미",
    "다함께 쿠키요미2 ～레이와～",
    "패밀리 트레이너",
    "R-TYPE FINAL2",
    "New 포켓몬 스냅",
    "Colorfall",
    "Skate City",
    "스윔아웃 (Swimout)",
    "던전마을 스토리(Dungeon Village)",
    "Fantasy Checkers",
    "Rip Them Off",
    "My Little Ice Cream Booth",
    "Lofi Ping Pong",
    "온천골 스토리(Hot Springs Story)",
    "게임개발 스토리(Game Dev Story)",
    "레전드 오브 키퍼즈（Legend of Keepers)",
    "Food Truck Tycoon - 푸드 트럭 타이쿤",
    "Arcaea",
    "A Fold Apart",
    "Jetboard Joust",
    "Manifold Garden",
    "애프터펄스",
    "호랑이 삼형제의 맛있는 여행",
    "(Tiger Trio's Tasty Travels)",
    "넛츠(NUTS)",
    "Godstrike",
    "Death end re;Quest",
    "언리얼 라이프 (UNREAL LIFE)",
    "카운터리콘 더 퍼스트 미션",
    "(Counter Recon: The First Mission)",
    "AKIBA'S TRIP: Hellbound & Debriefed",
    "대항해시대4 with 파워업키트 HD Version",
    "The Wanderer: Frankenstein’s Creature",
    "(방랑자 프랑켄슈타인의 창조물)",
    "inbento",
    "SnowRunner",
    "미토피아",
    "Knockout City™",
    "Maneater - 맨이터",
    "King of Seas",
    "마계전기DISGAEA６",
    "World's End Club",
    "이소로무스",
    "육각형 디펜스 (Hexagon Defense)",
    "Castle of no Escape",
    "PING REDUX",
    "Taxi Chaos",
    "크립트 오브 더 네크로댄서",
    "닌텐도 스위치 에디션",
    "디지복셀 지구방위군",
    "The Almost Gone",
    "다키스트 던전",
    "FIGHTING EX LAYER ANOTHER DASH",
    "SUPER BOMBERMAN R ONLINE",
    "포트 로얄 4",
    "스피릿 럭키의 위대한 모험",
    "(DreamWorks Spirit Lucky's Big Adventure)",
    "Wing of Darkness 유익의 프로일라인",
    "길잃은 고양이의 여행2 -Stray Cat Doors2-",
    "Dungeon Escape",
    "Qube Qross",
    "위체(Wicce)",
    "SpellKeeper",
    "농구리그 스토리(Basketball Club Story)",
    "Slide Stars 슬라이드 스타즈",
    "건물도 감정이 있어요!",
    "(Buildings Have Feelings Too!)",
    "헌티드던 더 좀비 아포칼립스",
    "(Haunted Dawn: The Zombie Apocalypse)",
    "Infinite Tanks WWII",
    "라스트 키즈 온 어스",
    "(The Last Kids on Earth and the Staff of Doom)",
    "Mighty Goose (마이티 구스)",
    "애니메이션 스토리(Anime Studio Story)",
    "별이 된 카이로군(Kairobotica)",
    "G1목장 스토리(Pocket Stables)",
    "어패럴 스토리(Pocket Clothier)",
    "스키장 스토리(Shiny Ski Resort)",
    "기획사 스토리♪(March to a Million)",
    "Kingdom Two Crowns",
    "아스트로 베어스",
    "Area 86",
    "알바: 야생의 모험",
    "쥬라기 월드 에볼루션: 컴플리트 에디션",
    "Piczle Cells",
    "다함께 쿠키요미3 -아버지가 아들에게-",
    "애니머스 레버넌트(ANIMUS: Revenant)",
    "차근차근 게임 코딩",
    "지역지 스토리(Magazine Mogul)",
    "게임센터 스토리(Pocket Arcade Story)",
    "농장 스토리(Pocket Harvest)",
    "She Sees Red - Interactive Movie",
    "곰아저씨 레스토랑",
    "Metal Unit",
    "데몽 헌터(Demong Hunter)",
    "LEGO® Builder's Journey",
    "ENDER LILIES: Quietus of the Knights",
    "Worms Rumble",
    "알렉스 키드 인 미라클 월드 DX",
    "(Alex Kidd in Miracle World DX)",
    "Very Very Valet",
    "Alchemist Adventure/알케미스트 어드벤처",
    "CarX Drift Racing Online",
    "만화가 스토리(The Manga Works)",
    "AnimaLudo",
    "아이, 좀비(I, Zombie)",
    "성검전설 Legend of Mana",
    "마리오 골프 슈퍼 러시",
    "Destroy All Humans!",
    "커브드 스페이스 (Curved Space)",
    "Sky - 빛의 아이들",
    "바운싱 히어로",
    "Roundguard",
    "Polyroll",
    "마이 디기 독 2",
    "드래곤 퀘스천",
    "Moto Rush GT",
    "Discolored 디스컬러드",
    "Sweet Bakery Tycoon - 스위트 베이커리 타이쿤",
    "A Plague Tale: Innocence - Cloud Version",
    "Ruvato : Original Complex",
    "Crash Drive 3",
    "Dark Fantasy: Jigsaw Puzzle",
    "대만 요괴 과일: 프롤로그",
    "영웅전설 섬의 궤적Ⅰ：Kai ",
    "–Thors Military Academy 1204-",
    "Boomerang X",
    "Graveyard Keeper",
    "S.N.I.P.E.R. - Hunter Scope",
    "미닛 오브 아일랜드",
    "몬스터헌터 스토리즈 2 파멸의 날개",
    "케이크 대소동",
    "케이크 대소동",
    "Dark Nights with Poe and Munro",
    "Moorhuhn Remake",
    "Classic Pool",
    "Klondike Solitaire - 클론다이크 솔리테어",
    "미로 대탐정: Pierre the Maze Detective",
    "키즈 플레이 동물 울음소리 게임",
    "키즈 플레이 성 탐험하기",
    "키즈 플레이 동물 카드 게임 & 카드 매칭 게임",
    "키즈 플레이 퍼즐: 동물과 자동차 등등",
    "키즈 플레이 형태 퍼즐",
    "순무 소년의 탈세 모험",
    "(Turnip Boy Commits Tax Evasion)",
    "Subnautica",
    "Subnautica: Below Zero",
    "Boomerang Fu",
    "Star Renegades",
    "Spelunker HD Deluxe",
    "RUINER",
    "Moorhuhn Wanted ",
    "Car Wash",
    "유아 및 어린이를 위한 자동차 및 트럭 차고 게임",
    "Zoo Dentist",
    "My Friend Pedro",
    "젤다의 전설 스카이워드 소드 HD",
    "헤노시스™",
    "크리스 테일즈",
    "포켓몬 유나이트",
    "신옥탑 메리스켈터 Finale",
    "Last Stop",
    "Ayo the Clown",
    "블래스터 마스터 제로 트릴로지",
    "Blaster Master Zero",
    "Blaster Master Zero 2",
    "Blaster Master Zero 3",
    "void tRrLM(); //보이드 테라리움",
    "Paint the Town Red",
    "마인드 메이즈",
    "Pizza Bar Tycoon - 피자 바 타이쿤",
    "Street Basketball - 길거리 농구",
    "바다표범 전철",
    "CLOSER",
    "드림하우스 스토리DX(Dream House Days DX)",
    "Fall Gummies",
    "Among Pipes",
    "엘디스트 소울",
    "Wolfenstein®: Youngblood™",
    "전장의 푸가",
    "（Fuga: Melodies of Steel）",
    "테니스 스토리(Tennis Club Story)",
    "그랑프리 스토리(Grand Prix Story)",
    "픽셀목장 스토리(8-Bit Farm)",
    "Royal Tower Defense",
    "A Monster's Expedition",
    "재벌도시 스토리(Venture Towns)",
    "아카데미 스토리2(Pocket Academy)",
    "PONPU 폰푸",
    "라멘 가게 스토리(The Ramen Sensei)",
    "Shadow Corridor 그림자 복도",
    "용의 별 바르니르 - Ecdysis of the dragon",
    "Dreamscaper",
    "영웅전설 섬의 궤적II：Kai ",
    "–The Erebonian Civil War-",
    "Eternum EX",
    "Doomsday Vault",
    "코만도스 2 HD 리마스터",
    "WINGSPAN (윙스팬)",
    "I.F.O",
    "도라에몽 진구의 신공룡",
    "Classic Games Collection Vol.1",
    "배틀 액스",
    "Curious Expedition 2",
    "Slime Rancher: Plortable Edition",
    "포어클로즈드 (Foreclosed)",
    "아웃 오브 라인 (Out of Line)",
    "로맨싱 사가 3",
    "Gryphon Knight Epic: Definitive Edition",
    "영화공방 스토리(Silver Screen Story)",
    "피라미드 스토리(The Pyraplex)",
    "다이묘 스토리(Oh! Edo Towns)",
    "회전초밥 스토리(The Sushi Spinnery)",
    "포켓 리그 스토리(Pocket League Story)",
    "크루즈선 스토리(World Cruise Story)",
    "아스트로 스토리(Epic Astro Story)",
    "백화점 스토리(Mega Mall Story)",
    "Lines Frenzy 라인 프렌지",
    "Checkers for Kids",
    "워터파크 스토리(Pool Slide Story)",
    "전국닌자 스토리(Ninja Village)",
    "Freecell Solitaire Deluxe",
    "프리셀 솔리테르 디럭스",
    "Doctor Who: The Lonely Assassins",
    "Princess Maker Go!Go! Princess",
    "Wrestledunk Sports",
    "버디 미션 BOND",
    "King's Bounty II",
    "프렌차이즈 스토리(Biz Builder Delux)",
    "대공원 스토리(Wild Park Manager)",
    "백화점 스토리2(Mega Mall Story 2)",
    "Totally Reliable Delivery Service",
    "걸즈 탱크 배틀(Girls Tank Battle)",
    "Inked: A Tale of love",
    "Urban Flow",
    "영웅전설: 시작의 궤적",
    "Salad Bar Tycoon 샐러드 바 타이쿤",
    "Spider Solitaire 스파이더 솔리테르",
    "팔코니어: 워리어 에디션",
    "(The Falconeer: Warrior Edition)",
    "체스 퍼즐 Knight Swap 2",
    "Townscaper",
    "섬주민: 콘솔 에디션",
    "NO MORE HEROES 3",
    "Secret Neighbor",
    "KEYWE",
    "A Good Snowman is Hard to Build",
    "Sokobond",
    "Funny Farm",
    "- 어린이와 유아를 위한",
    "재미있는 농장 동물 직소 퍼즐 게임",
    "맛집 스토리(Cafeteria Nipponica)",
    "Ravva and the Cyclops Curse",
    "파머스 코업：아웃오브 디스 월드",
    "흰색 소녀",
    "Mayhem Brawler",
    "룬 팩토리 5",
    "폐포",
    "냥자의 모험",
    "Escape First",
    "소닉 컬러즈 얼티밋",
    "울트라에이지",
    "Dice Legacy",
    "Knights & Guns",
    "Gabbuchi",
    "Killer Queen Black",
    "Super Cable Boy(슈퍼 케이블 보이)",
    "Escape First 2",
    "Escape First 3",
    "Dark Fantasy: Jigsaw Puzzle 2",
    "Curious Cases",
    "World for Two",
    "나뭇잎 아래",
    "Banners of Ruin",
    "NBA 2K22",
    "즐거움을 나눠라 메이드 인 와리오",
    "Truck Driver",
    "Flynn: Son of Crimson",
    "Tick Tock: A Tale for Two",
    "직소 걸작 EX 귀여운 여신",
    "(Jigsaw Masterpieces EXTENDED VERSION",
    "- Kawaii Cute Goddesses -)",
    "Evergate",
    "메탈릭 차일드",
    "Cruis'n Blast",
    "Catlateral Damage: Remeowstered",
    "Nexomon",
    "SkateBIRD",
    "리듬 피트니스 HOME FiT",
    "Project Winter",
    "Tails Of Iron",
    "림스 레이싱",
    "The Mean Greens - Plastic Warfare",
    "드래곤볼 Z 카카로트 + 새로운 각성 편",
    "Caligula２(칼리굴라2)",
    "엠버 (Embr)",
    "디아블로® II: 레저렉션™",
    "（Diablo® II: Resurrected™）",
    "Dandy Ace",
    "Hot Wheels Unleashed",
    "나쁜 왕과 훌륭한 용사",
    "Melty Blood: Type Lumina",
    "BARRICADEZ ReVisited",
    "애거서 크리스티",
    "에르퀼 푸아로: 첫 번째 사건",
    "Bonfire Peaks",
    "튀김 Splatter",
    "Aeon Drive",
    "Centipede: Recharged",
    "코튼 가디언 포스 새턴 트리뷰트",
    "가디언 포스 새턴 트리뷰트",
    "코튼 부메랑 새턴 트리뷰트",
    "코튼 2 새턴 트리뷰트",
    "Zotrix Starglider",
    "Escape 2088",
    "UNSIGHTED",
    "Rain on Your Parade: 찬물을 끼얹자!",
    "BARRICADEZ ReVisited",
    "Pancake Bar Tycoon 팬케이크 바 타이쿤",
    "Burger Chef Tycoon - 버거 셰프 타이쿤",
    "Enter the Gungeon (한국어판)",
    "Spelunky",
    "Spelunky 2",
    "몰래 하기 Stealth",
    "다크사이더스 III",
    "FIFA 22 Nintendo Switch™ Legacy Edition",
    "그란디아 HD 컬렉션 (GRANDIA HD Collection)",
    "퍼펙트! 슈퍼 몽키 볼 1&2 리메이크",
    "AAA 시계",
    "Super Arcade Soccer 2021",
    "Balloon Pop",
    "- 미취학 아동 및 유아를 위한 학습 게임 - ",
    "14개 언어로 숫자, 문자, 모양 및 색상 배우기",
    "Panmorphia",
    "Doki Doki Literature Club Plus! ",
    "(두근두근 문예부 플러스!)",
    "곰과 장군",
    "Drink More Glurp",
    "NO MORE HEROES 1+2",
    "No More Heroes",
    "No More Heroes 2: Desperate Struggle",
    "Tetris® Effect: Connected",
    "메트로이드 드레드",
    "Disco Elysium - The Final Cut",
    "Lumione",
    "Halloween Jigsaw Puzzles",
    "어린이 및 유아를 위한 ",
    "할로윈 직소 퍼즐 퍼즐 게임",
    "스페이스베이스 스타토피아",
    "(Spacebase Startopia)",
    "Immortus Temporus",
    "모나크/Monark",
    "Ruin Raiders",
    "Critadel",
    "파이트 오브 애니멀즈: 아레나",
    "(Fight of Animals: Arena)",
    "Hello Neighbor",
    "Bonito Days",
    "Knight's Retreat 체스 퍼즐: 나이츠 리트리트",
    "Aeon Must Die!",
    "Minigolf Adventure",
    "Sunblaze",
    "라스트 4 얼라이브 좀비로부터 탈출",
    "(Last 4 Alive: Escape From Zombies)",
    "Survival Z",
    "Dying Light Platinum Edition",
    "DJ 동물",
    "Creature in the Well",
    "Down in Bermuda (다운 인 버뮤다)",
    "스파클 2: EVO",
    "JARS",
    "Evertried",
    "Violett",
    "Tandem : A Tale of Shadows",
    "Timberman VS",
    "휴프노노츠",
    "Skul: The Hero Slayer",
    "Marvel's Guardians of the Galaxy",
    "Cloud Version",
    "The Suicide of Rachel Foster",
    "그린 피닉스",
    "Brain Meltdown - Into Despair",
    "에보랜드: 레전더리 에디션",
    "(Evoland: Legendary Edition)",
    "Happy Game (해피 게임)",
    "Fury Unleashed",
    "Black Widow: Recharged",
    "Niffelheim",
    "Tangle Tower",
    "슈퍼로봇대전30",
    "육각형",
    "Golf Club: Wasteland",
    "마리오 파티 슈퍼스타즈",
    "Unpacking 언패킹",
    "Kaze and the Wild Masks",
    "Where Cards Fall",
    "Encodya",
    "Stories Untold",
    "러슬러 (Rustler)",
    "Angry Alligator 앵그리 엘리게이터",
    "Tunche",
    "무한대경",
    "Pets No More 에어하키",
    "저스트 댄스 2022",
    "Airborne Kingdom",
    "10초 달리기 RETURNS",
    "Football Manager 2022 Touch",
    "좀비 이즈 플랜팅(Zombie Is Planting)",
    "진･여신전생5",
    "리듬 속 영어 BeatTalk",
    "Dadish",
    "Beyond Blue",
    "Grand Theft Auto: 트릴로지",
    "데피니티브 에디션",
    "The Wild At Heart",
    "그로우: 에버트리의 노래",
    "(Grow: Song of the Everthree)",
    "몰락한 왕: 리그 오브 레전드 이야기™",
    "마법공학 아수라장: 리그 오브 레전드 이야기™",
    "H.I.C.H.",
    "MARSUPILAMI - HOOBADVENTURE",
    "덤피 & 범피",
    "The Plane Effect",
    "ARIA CHRONICLE -아리아 크로니클-",
    "포켓몬스터",
    "브릴리언트 다이아몬드·샤이닝 펄",
    "WHAT THE GOLF?",
    "Crazy Trucks",
    "영웅전설 섬의 궤적 III",
    "Doctor Who: The Edge of Reality",
    "만화 색칠 공부 - 완전판",
    "사아아아아슴 시뮬레이터",
    "아주 흔한 사슴 이야기",
    "(DEEEER Simulator)",
    "BEYOND A STEEL SKY"
]

if(typeof module!=='undefined' && module.exports) module.exports = testdata
